use crate::model::{FpmSettings, Plan, ProcessManager};
use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

pub fn render_overrides(plan: &Plan, output_root: &Path) -> Result<Vec<PathBuf>> {
    if !plan.feasible {
        bail!("refusing to render an infeasible plan");
    }
    let mut groups: BTreeMap<&Path, Vec<_>> = BTreeMap::new();
    for d in &plan.pools {
        if d.selected && d.current != d.proposed {
            groups.entry(&d.id.directory).or_default().push(d);
        }
    }
    let mut written = Vec::new();
    for (dir, decisions) in groups {
        let safe = dir
            .to_string_lossy()
            .trim_start_matches('/')
            .replace('/', "__");
        let target_dir = output_root.join(if safe.is_empty() { "root" } else { &safe });
        fs::create_dir_all(&target_dir)?;
        let target = target_dir.join(crate::inventory::GENERATED_FILE);
        let mut content = String::from("; Generated by FPM Lens. Review before installation.\n");
        for d in decisions {
            content.push_str(&format!("\n[{}]\n", d.id.name));
            append_changes(&mut content, &d.current, &d.proposed);
        }
        atomic_write(&target, content.as_bytes())?;
        written.push(target);
    }
    Ok(written)
}

pub fn plan_digest(plan: &Plan) -> Result<String> {
    let bytes = serde_json::to_vec(plan)?;
    Ok(format!("{:x}", Sha256::digest(bytes)))
}

fn append_changes(out: &mut String, old: &FpmSettings, new: &FpmSettings) {
    field(
        out,
        "pm.max_children",
        old.max_children,
        new.max_children,
        false,
    );
    field(
        out,
        "pm.max_requests",
        old.max_requests,
        new.max_requests,
        false,
    );
    field(
        out,
        "pm.process_idle_timeout",
        old.process_idle_timeout_seconds,
        new.process_idle_timeout_seconds,
        true,
    );
    field(
        out,
        "request_terminate_timeout",
        old.request_terminate_timeout_seconds,
        new.request_terminate_timeout_seconds,
        true,
    );
    if new.pm == ProcessManager::Dynamic {
        field(
            out,
            "pm.start_servers",
            old.start_servers,
            new.start_servers,
            false,
        );
        field(
            out,
            "pm.min_spare_servers",
            old.min_spare_servers,
            new.min_spare_servers,
            false,
        );
        field(
            out,
            "pm.max_spare_servers",
            old.max_spare_servers,
            new.max_spare_servers,
            false,
        );
    }
}
fn field(out: &mut String, name: &str, old: Option<u32>, new: Option<u32>, seconds: bool) {
    if new.is_some() && new != old {
        out.push_str(&format!(
            "{name} = {}{}\n",
            new.unwrap_or_default(),
            if seconds { "s" } else { "" }
        ));
    }
}
fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    let parent = path.parent().context("output path has no parent")?;
    let mut temp = tempfile_path(
        parent,
        path.file_name()
            .and_then(|v| v.to_str())
            .unwrap_or("output"),
    );
    let mut attempt = 0;
    while temp.exists() {
        attempt += 1;
        temp = tempfile_path(parent, &format!("output-{attempt}"));
    }
    let mut file = fs::OpenOptions::new()
        .create_new(true)
        .write(true)
        .open(&temp)?;
    file.write_all(bytes)?;
    file.sync_all()?;
    fs::rename(&temp, path).with_context(|| format!("could not install {}", path.display()))?;
    Ok(())
}
fn tempfile_path(parent: &Path, stem: &str) -> PathBuf {
    parent.join(format!(".{stem}.{}.tmp", std::process::id()))
}
