use crate::model::{FpmSettings, Plan, ProcessManager};
use anyhow::{Context, Result, bail};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

const MANIFEST: &str = "fpm-lens-render-manifest.json";
const MAX_MANIFEST_BYTES: u64 = 1024 * 1024;

#[derive(serde::Serialize, serde::Deserialize, Default)]
#[serde(deny_unknown_fields)]
struct Manifest {
    files: Vec<ManifestFile>,
}

#[derive(serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct ManifestFile {
    staged: String,
    source_directory: PathBuf,
}

pub fn render_overrides(plan: &Plan, output_root: &Path) -> Result<Vec<PathBuf>> {
    crate::artifact::validate_plan(plan)?;
    fs::create_dir_all(output_root)?;
    reject_symlink(output_root)?;
    let old_manifest = load_manifest(output_root)?;
    let mut groups: BTreeMap<&Path, Vec<_>> = BTreeMap::new();
    for d in &plan.pools {
        if d.selected && d.current != d.proposed {
            groups.entry(&d.id.directory).or_default().push(d);
        }
    }
    let mut written = Vec::new();
    let mut manifest = Manifest::default();
    for (dir, decisions) in groups {
        let safe = format!("{:x}", Sha256::digest(dir.as_os_str().as_encoded_bytes()));
        let relative = PathBuf::from("pools")
            .join(safe)
            .join(crate::inventory::GENERATED_FILE);
        let target_dir = output_root.join(relative.parent().context("invalid staged path")?);
        reject_existing_symlink_chain(output_root, &target_dir)?;
        fs::create_dir_all(&target_dir)?;
        let target = target_dir.join(crate::inventory::GENERATED_FILE);
        let mut content = String::from("; Generated by FPM Lens. Review before installation.\n");
        for d in decisions {
            content.push_str(&format!("\n[{}]\n", d.id.name));
            append_changes(&mut content, &d.current, &d.proposed);
        }
        atomic_write(&target, content.as_bytes())?;
        manifest.files.push(ManifestFile {
            staged: relative.to_string_lossy().into_owned(),
            source_directory: dir.to_path_buf(),
        });
        written.push(target);
    }
    remove_stale(output_root, &old_manifest, &manifest)?;
    atomic_write(
        &output_root.join(MANIFEST),
        &serde_json::to_vec_pretty(&manifest)?,
    )?;
    Ok(written)
}

fn load_manifest(root: &Path) -> Result<Manifest> {
    let path = root.join(MANIFEST);
    if !path.exists() {
        return Ok(Manifest::default());
    }
    let bytes = crate::fsutil::read_limited(&path, MAX_MANIFEST_BYTES, "render manifest")?;
    serde_json::from_slice(&bytes).context("invalid existing render manifest")
}

fn remove_stale(root: &Path, old: &Manifest, new: &Manifest) -> Result<()> {
    for entry in &old.files {
        if new.files.iter().any(|new| new.staged == entry.staged) {
            continue;
        }
        let relative = Path::new(&entry.staged);
        let parts: Vec<_> = relative.components().collect();
        let valid = parts.len() == 3
            && parts[0].as_os_str() == "pools"
            && parts[1].as_os_str().to_str().is_some_and(|value| {
                value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
            })
            && parts[2].as_os_str() == crate::inventory::GENERATED_FILE;
        if !valid {
            bail!("unsafe path in existing render manifest");
        }
        let path = root.join(relative);
        if path.is_file() {
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

fn reject_symlink(path: &Path) -> Result<()> {
    if fs::symlink_metadata(path)?.file_type().is_symlink() {
        bail!("refusing symlinked output directory {}", path.display());
    }
    Ok(())
}

fn reject_existing_symlink_chain(root: &Path, target: &Path) -> Result<()> {
    let relative = target
        .strip_prefix(root)
        .context("staged path escaped output root")?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        current.push(component);
        if current.exists() {
            reject_symlink(&current)?;
        }
    }
    Ok(())
}

pub fn plan_digest(plan: &Plan) -> Result<String> {
    let bytes = serde_json::to_vec(plan)?;
    Ok(format!("{:x}", Sha256::digest(bytes)))
}

fn append_changes(out: &mut String, old: &FpmSettings, new: &FpmSettings) {
    field(
        out,
        "pm.max_children",
        old.max_children,
        new.max_children,
        false,
    );
    field(
        out,
        "pm.max_requests",
        old.max_requests,
        new.max_requests,
        false,
    );
    field(
        out,
        "pm.process_idle_timeout",
        old.process_idle_timeout_seconds,
        new.process_idle_timeout_seconds,
        true,
    );
    field(
        out,
        "request_terminate_timeout",
        old.request_terminate_timeout_seconds,
        new.request_terminate_timeout_seconds,
        true,
    );
    if new.pm == ProcessManager::Dynamic {
        field(
            out,
            "pm.start_servers",
            old.start_servers,
            new.start_servers,
            false,
        );
        field(
            out,
            "pm.min_spare_servers",
            old.min_spare_servers,
            new.min_spare_servers,
            false,
        );
        field(
            out,
            "pm.max_spare_servers",
            old.max_spare_servers,
            new.max_spare_servers,
            false,
        );
    }
}
fn field(out: &mut String, name: &str, old: Option<u32>, new: Option<u32>, seconds: bool) {
    if new.is_some() && new != old {
        out.push_str(&format!(
            "{name} = {}{}\n",
            new.unwrap_or_default(),
            if seconds { "s" } else { "" }
        ));
    }
}
fn atomic_write(path: &Path, bytes: &[u8]) -> Result<()> {
    let parent = path.parent().context("output path has no parent")?;
    let stem = path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("output");
    let mut attempt = 0_u32;
    let (temp, mut file) = loop {
        let temp = tempfile_path(parent, stem, attempt);
        match fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temp)
        {
            Ok(file) => break (temp, file),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                attempt = attempt.checked_add(1).context("too many staged files")?;
            }
            Err(error) => return Err(error.into()),
        }
    };
    let result = (|| -> Result<()> {
        file.write_all(bytes)?;
        file.sync_all()?;
        fs::rename(&temp, path).with_context(|| format!("could not install {}", path.display()))?;
        fs::File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result?;
    Ok(())
}
fn tempfile_path(parent: &Path, stem: &str, attempt: u32) -> PathBuf {
    parent.join(format!(".{stem}.{}.{attempt}.tmp", std::process::id()))
}
